# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectPdfs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdfsDialog(object):
    def setupUi(self, pdfsDialog):
        pdfsDialog.setObjectName("pdfsDialog")
        pdfsDialog.resize(390, 230)
        self.pdfLlistWidget = QtWidgets.QListWidget(pdfsDialog)
        self.pdfLlistWidget.setGeometry(QtCore.QRect(10, 10, 370, 181))
        self.pdfLlistWidget.setObjectName("pdfLlistWidget")
        self.addButton = QtWidgets.QPushButton(pdfsDialog)
        self.addButton.setGeometry(QtCore.QRect(20, 195, 45, 20))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setObjectName("addButton")
        self.removeButton = QtWidgets.QPushButton(pdfsDialog)
        self.removeButton.setGeometry(QtCore.QRect(70, 195, 65, 20))
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setObjectName("removeButton")
        self.okButton = QtWidgets.QPushButton(pdfsDialog)
        self.okButton.setGeometry(QtCore.QRect(280, 195, 90, 25))
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okButton.setObjectName("okButton")
        self.folderButton = QtWidgets.QPushButton(pdfsDialog)
        self.folderButton.setGeometry(QtCore.QRect(170, 195, 105, 25))
        self.folderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.folderButton.setObjectName("folderButton")

        self.retranslateUi(pdfsDialog)
        QtCore.QMetaObject.connectSlotsByName(pdfsDialog)

    def retranslateUi(self, pdfsDialog):
        _translate = QtCore.QCoreApplication.translate
        pdfsDialog.setWindowTitle(_translate("pdfsDialog", "Select pdfs to be watermarked"))
        self.addButton.setText(_translate("pdfsDialog", "Add pdf"))
        self.removeButton.setText(_translate("pdfsDialog", "Remove pdf"))
        self.okButton.setText(_translate("pdfsDialog", "Watermark pdfs"))
        self.folderButton.setText(_translate("pdfsDialog", "Select output folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pdfsDialog = QtWidgets.QDialog()
    ui = Ui_pdfsDialog()
    ui.setupUi(pdfsDialog)
    pdfsDialog.show()
    sys.exit(app.exec_())
